application: mealplanpp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: static/assets

- url: /.*
  script: routing.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
