# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'MealPlanCust' do
pod 'Stripe'
pod 'PaymentKit'
end

target 'MealPlanCustTests' do

end

